import type { CheerGuide } from '../types';
import { L, cheer } from '../types';

/** Extracted from Taiwan Midzy Union CAKE guide — white text = lyric, white-box dark text = cheer */
const LEFT = [
  L(cheer("(欢呼)")),
  L(cheer("ITZY, MIDZY, like that!")),
  L("Cake, cake, cake, cake, cake"),
  L("It's a piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("Cake, cake, cake, cake, cake"),
  L("Yeah, piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("(Ooh-wee) la, la-la-la, la-la-la, la"),
  L("(Ooh-wee) la, la-la-la, la-la-la"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
  L("yeah, like"),
  L("Cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("하늘은 참 파래 또 내 시간은 never waits"),
  L("똑같은 건 뻔해 또 다른 걸 난 원해 chase"),
  L("어떻게 모두 다 맞춰줘"),
  L("존중해 줘, I do me, you do you"),
  L(cheer("너는 너, 나는 나 (嫩嫩拿嫩拿), "), "좋잖아"),
  L(cheer("Cake, cake, "), "can't wait 'til I bite them"),
  L("어차피 인생은 내꺼 ", cheer("(니꺼) (逆購)")),
  L(cheer("Baam, baam, "), "can't wait 'til I shoot them"),
  L("뭘 그리 복잡해 매번 ", cheer("(매번) (妹蹦)")),
  L("Shake it, shake, ", cheer("shake it, shake, shake it, shake")),
  L(cheer("Bust it up, bust it up, bust it up")),
  L("우린 너무나 바빠, yeah, like my birthday"),
  L("Maybe 쉽지 않아 ", cheer("anyway")),
  L("생각대로 ", cheer("every day")),
  L("고민 고민 ", cheer("대신에 (得心餒)")),
  L("나만 생각 ", cheer("해 이제 (嘿一接)")),
  L("다 괜찮아, 어때 껌이라고 난 생각해"),
  L("Alright, alright"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
  L("yeah, like"),
  L("Cake, cake, cake, cake, cake"),
  L("It's a piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("Cake, cake, cake, cake, cake"),
  L("Yeah, piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("(Ooh-wee) la, la-la-la, la-la-la, la"),
  L("(Ooh-wee) la, la-la-la, la-la-la"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
];

const RIGHT = [
  L("yeah, like"),
  L("Cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("장담 못 해 날씨처럼, it's up in the air"),
  L("내일도 너 행복할지 who can guarantee it, so"),
  L(cheer("A T M, "), "지금이 훨씬 중요해"),
  L(cheer("Yeah, your way, "), "just live it up 'cause"),
  L("Maybe 쉽지 않아 ", cheer("anyway")),
  L("생각대로 ", cheer("every day")),
  L("고민 고민 ", cheer("대신에 (得心餒)")),
  L("나만 생각 ", cheer("해 이제 (嘿一接)")),
  L("다 괜찮아, 어때 껌이라고 난 생각해"),
  L("Alright, alright"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
  L("yeah, like"),
  L("Cake, cake, cake, cake, cake"),
  L("It's a piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("Cake, cake, cake, cake, cake"),
  L("Yeah, piece of cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L("(Ooh-wee) la, la-la-la, la-la-la, la"),
  L("(Ooh-wee) la, la-la-la, la-la-la"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
  L("yeah, like"),
  L("Cake, cake, cake, cake, cake ", cheer("(cake!)")),
  L(cheer("(欢呼)")),
  L("Sometimes, sometimes"),
  L("시원한 바람을 원해"),
  L("힘이 더 날지 몰라"),
  L("Sometimes, sometimes"),
  L("가끔 무관심이 편해"),
  L(cheer("(Ay) "), "누구든 들리게 말해"),
  L(cheer("(Ay) "), "쉽게 좀 생각해 like that"),
  L("Maybe 쉽지 않아 ", cheer("anyway")),
  L("생각대로 ", cheer("every day")),
  L("고민 고민 ", cheer("대신에 (得心餒)")),
  L("나만 생각 ", cheer("해 이제 (嘿一接)")),
  L("다 괜찮아, 어때 껌이라고 난 생각해"),
  L("Alright, alright"),
  L(cheer("왕 하고 먹어버려 다 (王哈辜某溝波溜大),")),
  L(cheer("yeah, like (cake!)")),
  L(cheer("(欢呼)")),
];

export const cakeGuide: CheerGuide = {
  slug: "cake",
  title: "<CAKE> 应援法",
  credit: "TAIWAN MIDZY UNION",
  accent: "orange",
  columns: [LEFT, RIGHT],
};
