import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

/** Extracted from Taiwan Midzy Union DALLA DALLA guide — white = lyric, pink = cheer */
const LEFT = [
  L(echo("\\歡呼\\")),
  L("다달라달라달라 다달라달라달라"),
  L(cheer("Yeji Lia Ryujin Chaeryeong Yuna ITZY DALLA DALLA")),
  L("People look at me and they tell me"),
  L("외모만 보고 내가 날라리 같대요"),
  L(cheer("So what? "), "신경 안 써"),
  L("I'm sorry, I ", cheer("don't care, don't care")),
  L("Really don't care, because"),
  L("사랑 따위에 목매지 않아 ", cheer("(hey!)")),
  L("세상엔 재밌는 게 더 많아 ", cheer("(hey!)")),
  L("언니들이 말해 철들려면 멀었대"),
  L("I'm ", cheer("sorry, sorry "), "철들 생각 없어요 nope!"),
  L("예쁘기만 하고 매력은 없는"),
  L("애들과 난 ", cheer("달라 달라 달라 (打蠟打蠟打蠟)")),
  L("네 기준에 날 맞추려 하지 마"),
  L("난 지금 내가 ", cheer("좋아 나는 나야 (啾哇 拿嫩 拿呀)")),
  L("I love myself 난 뭔가 ", cheer("달라 달라 yeah (打蠟打蠟耶)")),
  L("I love myself 난 뭔가 ", cheer("달라 달라 yeah (打蠟打蠟耶)")),
  L("난 너랑 달라 달라"),
  L("Bad, bad, I'm sorry I'm ", cheer("bad,")),
  L("I'm just the way I ", cheer("am")),
  L("남 신경 쓰고 살긴 아까워"),
  L("하고 싶은 일 하기도 바빠"),
  L("My life ", cheer("(my life)")),
  L("내 맘대로 살 거야 말리지 마 ", cheer("(말리지 마) (麻里肌馬)")),
  L("난 특별하니까, ", cheer("yeah")),
  L("남들의 시선 중요치 않아 ", cheer("(hey!)")),
  L("내 style이 좋아 그게 나니까 ", cheer("(hey!)")),
  L("언니들이 말해 내가 너무 당돌하대"),
  L("I'm ", cheer("sorry, sorry "), "바꿀 생각 없어요 nope!"),
  L("예쁘기만 하고 매력은 없는"),
  L("애들과 난 달라 ", cheer("달라 달라 (打蠟打蠟打蠟)")),
  L("네 기준에 날 맞추려 하지 마"),
  L("난 지금 내가 ", cheer("좋아 나는 나야 (啾哇 拿嫩 拿呀)")),
];

const RIGHT = [
  L(echo("\\歡呼/")),
  L("Don't care what people say, 나는 내가 알아"),
  L("I'm talkin' to myself 기죽지 마 절대로"),
  L("고개를 들고 네 꿈을 쫓아"),
  L("Just keep on dreamin', woah"),
  L("Keep your chin up, ", cheer("we got your back"), " (hey)"),
  L("Keep your head up ", cheer("just keep on dreamin'"), " (yeah)"),
  L("Keep your chin up, ", cheer("we got your back"), " (hey)"),
  L("Keep your head up ", cheer("just keep on dreamin'"), " (everybody)"),
  L(echo("\\歡呼/")),
  L("예쁘기만 하고 매력은 없는"),
  L("애들과 난 ", cheer("달라 달라 달라 (打蠟打蠟打蠟)")),
  L("네 기준에 날 맞추려 하지 마"),
  L("난 지금 내가 ", cheer("좋아 나는 나야 (啾哇 拿嫩 拿呀)")),
  L("I love myself (hey!)"),
  L("난 뭔가 ", cheer("달라 달라 (打蠟打蠟)"), " , yeah (oh, oh-oh)"),
  L("I love myself (hey!)"),
  L("난 뭔가 ", cheer("달라 달라 (打蠟打蠟)"), " , yeah"),
  L("난 너랑 달라 달라, yeah"),
  L(cheer("(달라달라) (打蠟打蠟)")),
  L(echo("\\歡呼/")),
];

export const dallaDallaGuide: CheerGuide = {
  slug: "dalla-dalla",
  title: "<DALLA DALLA> 应援法",
  credit: "TAIWAN MIDZY UNION",
  accent: "pink",
  columns: [LEFT, RIGHT],
};
