import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
  L(cheer("Ah ya ya ya")),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
  L(cheer("Ah ya ya ya")),
  L("Street 위로 당긴 trigger"),
  L(echo("(trigger)")),
  L("불이 붙어 버린 심장"),
  L(cheer("(심장)")),
  L("Giddy giddy here we go my friend"),
  L("Ooh, ooh, ooh 나를 구원해 줄 hero"),
  L(echo("(hero)")),
  L("따윈 원치 않는 ego"),
  L(echo("(ego)")),
  L("기다리는 건 not my way"),
  L("I slay, I slay, I slay"),
  L(cheer("(欢呼!!!)")),
  L("두 손에 꽉 움켜쥔 내 모든 걸 throw it all"),
  L("기꺼이 난 drop"),
  L("너의 손을 대신 hold"),
  L("이건 우리라는 syndrome"),
  L("We're gonna paint the void"),
  L("Count ", cheer("3, 2, 1")),
  L("We all scream"),
  L(cheer("(欢呼!!!)")),
  L("Let me hear you sing"),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
  L(cheer("Ah ya ya ya")),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
];

const RIGHT = [
  L(cheer("Ah ya ya ya, ah ya ya ya")),
  L("세상에 울린 our siren"),
  L("잠든 열기를 깨워내"),
  L(cheer("Ah ya ya ya, ah ya ya ya")),
  L("Count ", cheer("3, 2, 1")),
  L("We all scream"),
  L(cheer("(欢呼!!!)")),
  L("Girls will be girls yeah"),
  L("현실이란 때론 ", cheer("black out")),
  L("All the way downtown to the city"),
  L("You'll be alright"),
  L("그때마다 네 손 잡아줄 나이니"),
  L(cheer("Finally "), "하나가 된 우릴"),
  L(cheer("Who can block? "), "We'll keep going on"),
  L("Woo woo woo Ah, we’re"),
  L(cheer("(欢呼!!!)")),
  L("깨진 유리 위라 해도 딛고 서 hit the road"),
  L("기꺼이 난 go"),
  L("너와 함께라면 glow"),
  L("커져가는 our synergy"),
  L("한 걸음마다 blow"),
  L("Count ", cheer("3, 2, 1")),
  L("We all scream"),
  L(cheer("(欢呼!!!)")),
  L("Girls will be girls yeah"),
  L("Girls will be"),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜)")),
  L(cheer("(Itzy ! girls ! girls ! girls ! ggggirls ! )")),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
  L(cheer("Ah ya ya ya")),
  L("Girls will be girls will be"),
  L("girls will be girls will be"),
  L("Girls will be girls will be"),
  L("girls will be girls"),
  L(cheer("Ah ya ya ya, ah ya ya ya")),
  L("더 크게 울릴 our siren"),
  L("함께 가줄게 to the end"),
  L(cheer("Ah ya ya ya, ah ya ya ya")),
  L("Count ", cheer("3, 2, 1")),
  L("We all scream"),
  L("Girls will be girls yeah"),
];

export const girlsWillBeGirlsGuide: CheerGuide = {
  slug: "girls-will-be-girls",
  title: "<Girls Will Be Girls> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "cyan",
  columns: [LEFT, RIGHT],
};
