import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜)")),
  L(cheer("(Itzy! Who are you?)")),
  L("Who am I? The revolution"),
  L("깨어난 ", cheer("your illusion")),
  L("상상 속에 your illusion"),
  L("Oh 너의 ", cheer("상상 속에")),
  L("존재해 상상 속에"),
  L("숨쉬는 ", cheer("fallen angel")),
  L("Who am I? ", cheer("fallen angel")),
  L("Oh I'm a fallen angel ", cheer("and I said")),
  L(cheer("(欢呼!!!)")),
  L("Call out my name"),
  L("in the middle of the night"),
  L("두려워 ", cheer("마 call out my name")),
  L("call out my name yeah"),
  L("Call out my name"),
  L("in the middle of the night"),
  L("두려워 ", cheer("마 call out my name")),
  L("You know, I'm"),
  L("your imaginary friend"),
  L("You know, I'm"),
  L("밤새 너의 곁에서"),
  L("When there's monsters"),
  L("on your ceiling"),
  L("I'll keep you safe and"),
  L("꿈을 꿀 수 있게"),
  L("You know, I'm"),
  L("your imaginary friend"),
  L("You know, I'm"),
  L("It's you and I until the end"),
  L(cheer("(Itzy! Midzy!)")),
  L(cheer("(欢呼!!!)")),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜)")),
  L(cheer("(Itzy! Who are you?)")),
];

const RIGHT = [
  L("Who am I? The evolution"),
  L("기억 안에 ", cheer("존재해")),
  L("네 맘속 hallucination"),
  L("Oh 너의 ", cheer("상상 속에")),
  L("Come on and ", cheer("dance, dance")),
  L("and don't stop"),
  L("작은 나의 ", cheer("lucky spark")),
  L("네게 힘이 ", cheer("될 거야")),
  L("We gon ", cheer("ride and run")),
  L("can't stop thinking about our vibe"),
  L("Jump ", cheer("we can run")),
  L("and I'm killing it to the top yeah"),
  L(cheer("(欢呼!!!)")),
  L("Call out my name"),
  L("in the middle of the night"),
  L("두려워 ", cheer("마 call out my name")),
  L("call out my name yeah"),
  L("Call out my name"),
  L("in the middle of the night"),
  L("두려워 ", cheer("마 call out my name")),
  L("You know, I'm"),
  L("your imaginary friend"),
  L("You know, I'm"),
  L("밤새 너의 곁에서"),
  L("When there's monsters"),
  L("on your ceiling"),
  L("I'll keep you safe and"),
  L("꿈을 꿀 수 있게"),
  L("You know, I'm"),
  L("your imaginary friend"),
  L("You know, I'm"),
  L("It's you and I until the end"),
  L(cheer("(欢呼!!!)")),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜)")),
  L(cheer("(Itzy! Midzy!)")),
];

export const imaginaryFriendGuide: CheerGuide = {
  slug: "imaginary-friend",
  title: "<Imaginary Friend> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "pink",
  columns: [LEFT, RIGHT],
};
