import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L("Did you hear that? ", cheer("(what)")),
  L("So did you hear that? ", cheer("(what)")),
  L("So did you hear that? ", cheer("(what)")),
  L("So what do you think?"),
  L("눈길이 your lips"),
  L("아직은 아냐 ", cheer("娜nia")),
  L("수다스런 gossip"),
  L("시선은 ", cheer("시선 시선")),
  L("난 오직 focus on me"),
  L("말해줘 뭐가 문제인지 말해줘"),
  L("Can't you see?"),
  L("더는 못 참아 이제는 now now"),
  L(cheer("(欢呼!!!)")),
  L("미안하다고 말 안 해 I’m not sorry"),
  L("그냥은 안 돼 ", cheer("let it slide ay")),
  L("시선은 내 sight"),
  L("더 원해 more"),
  L("Worth it, worth it"),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L("Come and ", cheer("kiss & tell")),
  L("난 괜찮아 don’t mind"),
  L("Come and ", cheer("kiss & tell")),
  L("말해줘 솔직히"),
  L("Nothing you can tell"),
  L("말해봐 뭐라 해도 but"),
  L(cheer("I don't talk, let 'em talk, nah")),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L("Did you hear that? ", cheer("(what)")),
  L("So did you hear that? ", cheer("(what)")),
  L("So did you hear that? ", cheer("(what)")),
  L("So what do you think?"),
  L("유혹적인 너의 temptation"),
  L("지배적인 domination"),
  L("바쁜 척 busy"),
  L("말해봐 뭐라 해도 말해봐"),
  L("Keep saying"),
  L("난 멈출 수 없어 you can never stop me"),
  L(cheer("(欢呼!!!)")),
  L("미안하다고 말 안 해 I’m not sorry"),
  L("그냥은 안 돼 ", cheer("let it slide ay")),
  L("시선은 내 sight 더 원해 more"),
  L("Worth it, worth it"),
  L("I bet you wanna know"),
  L("how we look this good like"),
];

const RIGHT = [
  L("Come and ", cheer("kiss & tell")),
  L("난 괜찮아 don’t mind"),
  L("Come and ", cheer("kiss & tell")),
  L("말해줘 솔직히"),
  L("Nothing you can tell"),
  L("말해봐 뭐라 해도 but"),
  L(cheer("I don't talk, let 'em talk, nah")),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L("We've been working it"),
  L("Doesn't matter come in"),
  L("말해 what is right"),
  L(cheer("Talking Talking")),
  L("It never stops"),
  L("말해봐 뭐라 해도 ", cheer("说 说!")),
  L("말해봐 뭐라 해도 ", cheer("说 说!")),
  L(cheer("Whatever, go")),
  L(cheer("Whoever, go")),
  L("말해봐 I’ll eat it up"),
  L(cheer("(欢呼!!!)")),
  L("말해봐 뭐라 해도 말해봐 right here"),
  L("I'll leave it all"),
  L("말해줘 ", cheer("back off me ay")),
  L("말해봐 솔직히"),
  L("난 계속 keep on"),
  L(cheer("Walking walking")),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L("Come and ", cheer("kiss & tell")),
  L("눈길이 your mind"),
  L("Come and ", cheer("kiss & tell")),
  L("아직은 my heart"),
  L("Nothing you can tell"),
  L("말해봐 뭐라 해도 but"),
  L(cheer("I don't talk, let 'em talk, nah")),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L(cheer("(欢呼!!!)")),
  L("Did you hear that?"),
  L("So did you hear that?"),
  L("So did you hear that?"),
  L("So what do you think?"),
  L("What do you think?"),
  L(cheer("kiss & tell")),
  L("Did you hear that?"),
  L("So did you hear that?"),
  L(cheer("I don't talk, let 'em talk, nah")),
  L("I bet you wanna know"),
  L("how we look this good like"),
  L(cheer("(欢呼!!!)")),
];

export const kissAndTellGuide: CheerGuide = {
  slug: "kiss-and-tell",
  title: "<Kiss & Tell> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "cyan",
  columns: [LEFT, RIGHT],
};
