import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L("Shhhhhhh"),
  L("Guess who loves you 나야 나 ", cheer("娜呀娜")),
  L("Do I show you? No? No ", cheer("No?No")),
  L("아직 Time? 아냐 난 ", cheer("娜nia 娜")),
  L("좀 더 가까이 좀 더 가까이 그러다 갑자기 싹 ", cheer("飒")),
  L("I'mma steal it 마음을 훔쳐"),
  L("You are gonna love me"),
  L("결정적일 때 이빨을 드러내는 Type"),
  L("나와 두 눈이 마주쳐도 난 흔들림이 없어 ", cheer("诺")),
  L("No 널 사랑하는 게 죄라면 범인은 No"),
  L("Who? You’ll never know"),
  L("Baby 헷갈려 헷갈려 ", cheer("헷갈려 헷갈려")),
  L("결국엔 내 거야"),
  L("내 거야 내 게 되겠지 넌 이제 ", cheer("헷갈려 헷갈려")),
  L("택할 시간이야"),
  L("벌써 어느새 ", cheer("Finally finally")),
  L("또 밤이 되었습니다"),
  L("택할 시간이야"),
  L("벌써 어느새 또 밤이 되었습니다"),
  L(cheer("택할")),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L(cheer("또 아침이 밝았습니다")),
  L(cheer("또 아침이 밝았습니다")),
  L("어젯밤에도 You don't even know"),
  L("누구일까 ", cheer("Mafia")),
  L("날이 밝아도 You don't even know"),
  L("누구일까 ", cheer("Mafia")),
  L("배우보다 더 배우 ", cheer("늑대")),
  L("늑대 가지고 노는 여우 ", cheer("여우")),
  L("전혀 안 보이겠지 Clue"),
  L("하지만 나에겐 다 계획이 있다고 Go"),
];

const RIGHT = [
  L("그만 머뭇머뭇대"),
  L("슬슬 작전 개시"),
  L("너를 뺏어 뺏어 뺏어 ", cheer("뺏어 뺏어")),
  L("Like a caper movie ", cheer("(Ready)")),
  L("알 수 없는 Poker face ", cheer("(face)")),
  L("점령해 네 맘 속 Place ", cheer("(Place)")),
  L("Hurry up Baby"),
  L("catch me if you can haha"),
  L("Baby 헷갈려 헷갈려 ", cheer("헷갈려 헷갈려")),
  L("결국엔 내 거야"),
  L("내 거야 내 게 되겠지 넌 이제 ", cheer("헷갈려 헷갈려")),
  L("택할 시간이야"),
  L("벌써 어느새 ", cheer("Finally finally")),
  L("또 밤이 되었습니다"),
  L("택할 시간이야"),
  L("벌써 어느새 또 밤이 되었습니다"),
  L(cheer("택할")),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L("누구일까 ", cheer("Mafia")),
  L(cheer("(欢呼!!!)")),
  L("마지막 밤이 깊었어 Baby"),
  L("이 밤이 지나면"),
  L("네 곁엔 나 하나 Yeah yeah"),
  L("마침내 피할 수 없는 아침이 와 Hahaha"),
  L(cheer("马! 匹! 啊!")),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L("I'm the mafia"),
  L("Ma ma ma ma ma mafia ya ya"),
  L("We do it like a mafia"),
  L(cheer("또 아침이 밝았습니다")),
  L(cheer("또 아침이 밝았습니다")),
  L("어젯밤에도 You don't even know"),
  L("누구일까 ", cheer("Mafia")),
  L("날이 밝아도 You don't even know"),
  L("누구일까 ", cheer("Mafia")),
  L(cheer("(欢呼!!!)")),
];

export const mafiaInTheMorningGuide: CheerGuide = {
  slug: "mafia-in-the-morning",
  title: "<In The Morning> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "red",
  columns: [LEFT, RIGHT],
};
