import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L("Mo mo mo mo mo motto"),
  L("Mo mo mo mo mo motto"),
  L("Mo mo mo mo mo motto"),
  L(cheer("(Itzy ! Midzy ! )")),
  L("You are my motto"),
  L("두 눈을 감아"),
  L("I can feel you by my side"),
  L("All the time oh yeah"),
  L("Make me fearless"),
  L("늘 소란한 어둠을 헤맬 때"),
  L("Got me in a trance 익숙한 너의 voice"),
  L(cheer("(사랑해)")),
  L("운명처럼 fallin’"),
  L("달라져 shift my callin’"),
  L("I know that you feel it, too"),
  L("You gotta trust me baby"),
  L("기다려줘 you’ll see"),
  L("끝내 닿을 너란 꿈"),
  L("You are my wish 날 이끌어 ", cheer("후")),
  L("You are the gleam 날 일으켜 ", cheer("하")),
  L("세상 끝에 서 있을 때"),
  L("Uh 환히 나를 비춰"),
  L(cheer("(欢呼!!!)")),
  L("Take me to a better place"),
  L("이 결말 따윈 not afraid"),
  L("Yeah I need you by my side"),
  L("Ready? ", cheer("dive in")),
  L("Take my hand"),
  L("Ain’t nobody like you"),
  L("I wanna be the one"),
  L("너를 향해 멈추지 않아"),
  L("Now I know"),
  L("널 닮아 눈부실 my everything"),
  L("날 비춘 너"),
  L("Want you so bad"),
  L("Cause you are my motto"),
  L(cheer("내가 네 Motto")),
  L(cheer("(Motto ! Midzy ! )")),
  L("너로 번져오는 delight ", cheer("(delight)")),
  L("끝이 어딘지는 몰라 ", cheer("(what ? )")),
  L("망설이던 밤은 over"),
  L("선명하게 빛나 clearly"),
  L("뜨거운 숨이 ", cheer("날")),
  L("데려가 swervin’"),
  L("세상 끝이라 해도 move"),
  L("I gotta stand 나를 던져 ", cheer("후")),
  L("Don’t hesitate 후회 없게 ", cheer("하")),
  L("Everyday, never look back"),
  L("Yeah 답은 오직 너야"),
  L(cheer("(欢呼!!!)")),
  L("Take me to a better place"),
  L("이 결말 따윈 not afraid"),
  L("Yeah I need you by my side"),
  L("Ready? ", cheer("dive in")),
];

const RIGHT = [
  L("Take my hand"),
  L("Ain’t nobody like you"),
  L("I wanna be the one"),
  L("너를 향해 멈추지 않아"),
  L("Now I know"),
  L("널 닮아 눈부실 my everything"),
  L("날 비춘 너"),
  L("Want you so bad"),
  L("Cause you are my motto"),
  L(cheer("내 가 네 Motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("You are my motto"),
  L(cheer("내 가 네 Motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L(cheer("(欢呼!!)")),
  L("You know, I know"),
  L("That I need your love"),
  L("Let’s call it us"),
  L("지금 순간도"),
  L(cheer("(欢呼!!!)")),
  L("함께한 시간의 끝에 ", cheer("내")),
  L("내 안을 ", cheer("something")),
  L("Call you any time when"),
  L("I need someone, you"),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜 Motto)")),
  L("Take me there like that"),
  L(cheer("(欢呼!!!)")),
  L("Take my hand"),
  L("Ain’t nobody like you"),
  L("I wanna be the one"),
  L("너를 향해 멈추지 않아"),
  L("As you know"),
  L("Feeling so meant to be 이 떨림이"),
  L("Don’t take it slow"),
  L("하나가 돼"),
  L(cheer("내 가 네 Motto")),
  L("Cause you are my motto"),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("You are my motto"),
  L(cheer("내 가 네 Motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L("Mo mo mo mo mo ", cheer("motto")),
  L(cheer("(Motto ! Itzy ! )")),
  L(cheer("(欢呼!!!)")),
];

export const mottoGuide: CheerGuide = {
  slug: "motto",
  title: "<Motto> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "blue",
  columns: [LEFT, RIGHT],
};
