import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(yeah)")),
  L("Not shy not me"),
  L(cheer("(Itzy ! Midzy ! Not shy ! 娜)")),
  L("난 빨리빨리 원하는 걸 말해"),
  L("못 가지면 어때 괜히 ", cheer("망설")),
  L("망설이다 시간만 가니"),
  L("Yeah 다 말할래"),
  L("cuz I like it cuz I ", cheer("like it like it")),
  L("기다려 왜 기다려서 뭐해"),
  L("내가 내 맘을 왜 왜 말하면 안 돼 ", cheer("yeah")),
  L("그냥 탁 ", cheer("탁탁탁탁탁")),
  L(cheer("탁탁탁탁탁")),
  L("Not shy to say I want you"),
  L("Hey there hey there 우리는 ", cheer("우리는")),
  L("Great pair great pair 네 맘이 ", cheer("뭔지")),
  L("모르지만 내 생각이 맞아"),
  L("그러니까 ", cheer("yeah yeah")),
  L("내 맘은 내 거 ", cheer("그러니까")),
  L("좋아한다고 ", cheer("자유니까")),
  L("네 맘은 네 거 ", cheer("맞으니까")),
  L("말해봐 다 어서 다 cuz I’m ", cheer("not shy")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("Give me 다 다다 ", cheer("다다다다다")),
  L(cheer("다다다다다")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("너를 원해 뭐 어때 cuz I’m ", cheer("not shy")),
  L(cheer("(欢呼!!!)")),
  L("넌 빨리빨리 대답할 필욘 없어"),
  L("어차피 내 거니까 woo"),
  L("날 보고 있기만 하면 돼"),
  L("Yeah you will like it cuz you like it"),
  L("Cuz you ", cheer("like it like it")),
  L("내가 미워 아니라면 비워"),
  L("다른 건 다 지워 내가 네 only one ", cheer("yeah")),
  L("그냥 싹 ", cheer("싹싹싹싹싹")),
  L(cheer("싹싹싹싹싹")),
  L("Not shy to say I want you"),
];

const RIGHT = [
  L("Hey there hey there 우리는 ", cheer("우리는")),
  L("Great pair great pair 네 맘이 ", cheer("뭔지")),
  L("모르지만 내 생각이 맞아"),
  L("그러니까 ", cheer("yeah yeah")),
  L("내 맘은 내 거 ", cheer("그러니까")),
  L("좋아한다고 ", cheer("자유니까")),
  L("네 맘은 네 거 ", cheer("맞으니까")),
  L("말해봐 다 어서 다 cuz I’m ", cheer("not shy")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("Give me 다 다다 ", cheer("다다다다다")),
  L(cheer("다다다다다")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("너를 원해 뭐 어때 cuz I’m ", cheer("not shy")),
  L(cheer("(欢呼!!!)")),
  L("후회하긴 싫으니까"),
  L("엔딩 상관없으니까"),
  L("Go go go 모두 쏟아내"),
  L("No yes no 뭐든지 어때"),
  L("이러면 저러면 어때"),
  L("어차피 안 될 거 빼고 다 돼"),
  L("Let’s just be who we are"),
  L("Do what we do 네 맘대로 해"),
  L("Let the beat drop"),
  L(cheer("(欢呼!!!)")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("말해봐 다 어서 다 cuz I’m ", cheer("not shy")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("Give me 다 다다 ", cheer("다다다다다")),
  L(cheer("다다다다다")),
  L("Not shy not me ", cheer("(ITZY)")),
  L("난 다 원해 다다 ", cheer("(not shy)")),
  L("Not shy not me"),
  L("너를 원해 뭐 어때 cuz I’m ", cheer("not shy")),
  L(cheer("Not shy not me")),
  L(cheer("(欢呼!!!)")),
];

export const notShyGuide: CheerGuide = {
  slug: "not-shy",
  title: "<Not Shy> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "orange",
  columns: [LEFT, RIGHT],
};
