import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

/** Extracted from Taiwan Midzy Union SNEAKERS guide — white = lyric, pink = cheer */
const LEFT = [
  L(cheer("Yeah, yeah")),
  L(cheer("Let's go (ITZY!)")),
  L("Like what?"),
  L("자유로운 기분, ", cheer("I like that")),
  L("고민 따윈 already ", cheer("done, done")),
  L("색안경 끼고 보는 게 죄지"),
  L("That's not my fault, ", cheer("woah")),
  L("Told ya I don't care at all"),
  L("내 멋대로 갈 거야"),
  L("필요 없어 order"),
  L("Don't need no guidance, I'm makin' my way"),
  L("I'm on my way up ", cheer("(cha-cha)")),
  L("Run to the top ", cheer("(ah, woo)")),
  L("난 언제든 straight up ", cheer("(alright)")),
  L("원래 두려운 게 없어 난"),
  L("상관없어, call me ", cheer("trouble")),
  L("Or you can call me ", cheer("weirdo")),
  L("나로 살고 ", cheer("싶어 (喜坡)")),
  L("턱 끝을 치켜올린 채로"),
  L("다 가질 듯한 attitude 그거면 돼"),
  L(cheer("(SNEAKERS!) (四!尼!克!斯!)")),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("Put my sneakers on"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("멀리 가보자고, yeah, yeah"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
  L("기다리던 순간, stand up, ", cheer("stand up")),
  L("빨리 뛰는 심장, don't stop, ", cheer("don't stop")),
  L("Get loose, 불태워 지금, my youth"),
  L("The party ain't started"),
  L("시작도 안 했어 난"),
  L("요즘 꽂힌 말이 하나 ", cheer("있지 (一擊)")),
  L("My best is ", cheer("yet to come")),
  L("상관없어, call me ", cheer("trouble")),
  L("Or you can call me ", cheer("weirdo")),
  L("나로 살고 ", cheer("싶어 (喜坡)")),
  L("턱 끝을 치켜올린 채로"),
  L("다 가질 듯한 attitude 그거면 돼"),
  L(cheer("(SNEAKERS!) (四!尼!克!斯!)")),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("Put my sneakers on"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("멀리 가보자고, yeah, yeah"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
];

const RIGHT = [
  L("자유롭게 뛰고 싶어 다른 사람 시선들, don't care now ", cheer("(hey, hey)")),
  L("어디까지 가게 될지 모르지만 일단은, start right now"),
  L("Yeah, ", cheer("alright")),
  L("멈추지 마 to the top"),
  L("Don't worry about it, 'cause you know I"),
  L(cheer("Put my sneakers on")),
  L(echo("\\歡呼/")),
  L("상관없어, call me trouble"),
  L("Or you can call me weirdo"),
  L("나로 살고 싶어"),
  L("턱 끝을 치켜 올린 채로"),
  L("다 가질 듯한 attitude 그거면 돼"),
  L(cheer("(Hwang Yeji, Choi Jisu, Shin Ryujin, Lee Chaeryeong, Shin Yuna, MIDZY)")),
  L(cheer("You better put your sneakers on")),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("Put my sneakers on"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
  L("Put my sneakers on"),
  L("하나, 둘, ready, ", cheer("get set, go")),
  L("Put my sneakers on"),
  L(cheer("put 'em up, put 'em up, "), "yeah, yeah"),
  L("자유롭게 뛰고 싶어 다른 사람"),
  L("시선들, don't care now ", cheer("(hey, hey)")),
  L("어디까지 가게 될지 모르지만"),
  L("일단은, start right now"),
  L("Yeah, ", cheer("alright")),
  L("멈추지 마 to the top"),
  L("같이 걸어 가보자고"),
  L(cheer("put 'em up, put 'em up, yeah, yeah")),
  L(cheer("ITZY! MIDZY! 날자! (ITZY! MIDZY! 耐架)")),
  L(echo("\\歡呼\\")),
];

export const sneakersGuide: CheerGuide = {
  slug: "sneakers",
  title: "<SNEAKERS> 应援法",
  credit: "TAIWAN MIDZY UNION",
  accent: "pink",
  columns: [LEFT, RIGHT],
};
