import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L(cheer("(黄礼志 崔智秀 申留真 李彩领 申有娜)")),
  L(cheer("(Itzy ! That's ! a ! no ! no ! )")),
  L("어떤 말을 해도 난 난 난"),
  L("내가 원하는 대로"),
  L("난 난 난 난 난"),
  L(cheer("拍手")),
  L("Well made label on my body"),
  L(cheer("Oooh move up faster faster")),
  L(cheer("Oooh gettin' louder louder")),
  L(cheer("Oooh 내 말대로 That's all")),
  L("뭐라 해도 Don’t ask no questions"),
  L(cheer("(欢呼!!!)")),
  L("뭐라 해도 내 말대로 말해"),
  L("Can't let you kill my vibe"),
  L(cheer("that's a no no")),
  L("Sorry, I beg your pardon"),
  L("뭐라 해도 내 말대로 I told ya"),
  L("That's a no no"),
  L(cheer("Hoo Ah ya ya ya ya")),
  L(cheer("Ha uh uh uh")),
  L(cheer("Hoo ah ya ya ya ya")),
  L("Do what I want Say what I wanna"),
  L(cheer("Hoo Ah ya ya ya ya")),
  L(cheer("Ha uh uh uh")),
  L(cheer("Hoo ah ya ya ya ya")),
  L("Do what I want Say what I wanna"),
  L("Hit that thang like a drum ", cheer("ta ta")),
  L("Rum pa pa pum pa pa pum ", cheer("pa pa")),
  L("뭐라 해도 내 말대로"),
  L("말해 ", cheer("说"), " 말해 ", cheer("说 说")),
  L(cheer("拍手")),
];

const RIGHT = [
  L("Blow that thang"),
  L("like a brass ", cheer("bam bam")),
  L("Rum pa pa pum pa pa pum ", cheer("pa pa")),
  L("뭐라 해도 내 말대로"),
  L("Say that's a ", cheer("no no"), " that's a ", cheer("no no")),
  L(cheer("(欢呼!!!)")),
  L("뭐라 해도 내 말대로"),
  L("뭐라 해도 That’s no, I’m sorry"),
  L("I'm gonna keep singing"),
  L("I'm gonna keep dancing"),
  L("뭐라 해도 내 말대로"),
  L(cheer("That's ! a ! no ! no !")),
  L("Hit that thang like a drum ", cheer("ta ta")),
  L("Rum pa pa pum pa pa pum ", cheer("pa pa")),
  L("뭐라 해도 내 말대로"),
  L("말해 ", cheer("说"), " 말해 ", cheer("说 说")),
  L(cheer("拍手")),
  L("Blow that thang"),
  L("like a brass ", cheer("bam bam")),
  L("Rum pa pa pum pa pa pum ", cheer("pa pa")),
  L("뭐라 해도 내 말대로"),
  L("Say that's a ", cheer("no no"), " that's a ", cheer("no no")),
  L(cheer("Hoo Ah ya ya ya ya")),
  L(cheer("Ha uh uh uh")),
  L(cheer("Hoo ah ya ya ya ya")),
  L("That's a no no"),
  L(cheer("Hoo Ah ya ya ya ya")),
  L(cheer("Ha uh uh uh")),
  L(cheer("Hoo ah ya ya ya ya")),
  L("That's a no no"),
  L(cheer("(欢呼!!!)")),
];

export const thatsANoNoGuide: CheerGuide = {
  slug: "that-s-a-no-no",
  title: "<THAT'S A NO NO> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "blue",
  columns: [LEFT, RIGHT],
};
