import type { CheerGuide } from '../types';
import { L, cheer, echo } from '../types';

const LEFT = [
  L(cheer("(欢呼!!!)")),
  L(cheer("Yeji Lia Ryujin Chaeryeong Yuna")),
  L(cheer("Itzy Wan!na!be!")),
  L("잔소리는 stop it ", cheer("Whoo!")),
  L("알아서 할게 ", cheer("Yeah!")),
  L("내가 뭐가 되든"),
  L("내가 알아서 할 테니까 ", cheer("좀")),
  L("I do what I wanna"),
  L(cheer("Pop! Pop! Pop!")),
  L("평범하게 살든 말든 내버려 둘래"),
  L("어차피 내가 살아 내 인생"),
  L("내거니까 ", cheer("내거니까")),
  L("I'm so ", cheer("bad bad"), " 차라리 이기적일래"),
  L("눈치 보느라 착한 척"),
  L("상처받는 것보다 ", cheer("백번 나아")),
  L(cheer("백번 나아")),
  L("I'm just on my way ", cheer("嗯~")),
  L("간섭은 no no ", cheer("ok ~")),
  L("말해버릴지도 몰라 너나 잘하라고"),
  L("누가 뭐라 해도 ", cheer("누가 뭐라")),
  L("난 나야 난 그냥"),
  L("내가 되고 싶어"),
  L("I wanna be ", cheer("me me me")),
  L("굳이 뭔가 될 필요는 없어"),
  L("난 그냥 나일 때 완벽하니까"),
  L("I wanna be ", cheer("me me me")),
  L("I don't wanna be somebody"),
  L("Just wanna be ", cheer("me be me")),
  L("I wanna be ", cheer("me me me")),
  L("I don't wanna be somebody"),
  L("Just wanna be ", cheer("me be me")),
  L("I wanna be ", cheer("me me me")),
  L(cheer("Ready Action")),
  L("Everybody everybody everybody"),
  L("teachin' me"),
  L(cheer("All eyes on me")),
  L("이래라 저래라 모두 한마디씩"),
  L(cheer("Don't touch me")),
];

const RIGHT = [
  L("Ah yeah ", cheer("yeah yeah yeah yeah")),
  L("내 앞가림은 내가 해"),
  L("I'm do my thing just do your thing"),
  L("Cuz I'm the ", cheer("one & only")),
  L("사람들은 남 말 하기를 좋아해"),
  L(cheer("啦~啦~啦~")),
  L("남의 인생에 뭔 관심이 많아 왜"),
  L(cheer("啦~啦~啦~")),
  L("저기 미안하지만 신경 좀 꺼줄래요"),
  L("It's none of your business"),
  L("I do my own business"),
  L(cheer("叮!")),
  L("누가 뭐라 해도 난 나야 난 그냥"),
  L("내가 되고 싶어"),
  L("I wanna be ", cheer("me me me")),
  L("굳이 뭔가 될 필요는 없어"),
  L("난 그냥 나일 때 완벽하니까"),
  L("I wanna be ", cheer("me me me")),
  L(cheer("Hey ! Hey !")),
  L("No matter if you love me or hate me"),
  L(cheer("Hey ! Hey !")),
  L("I wanna be me"),
  L("One and only me"),
  L("If you feel me turn this beat up"),
  L("I wanna be ", cheer("me me me")),
  L("누가 뭐라 해도 난 나야 난 그냥"),
  L("내가 되고 싶어"),
  L("I wanna be ", cheer("me me me")),
  L("굳이 뭔가 될 필요는 없어"),
  L("난 그냥 나일 때 완벽하니까"),
  L("I wanna be ", cheer("me me me")),
  L(cheer("I don't wanna be somebody")),
  L(cheer("Just wanna be me be me")),
  L(cheer("I wanna be me me me")),
  L(cheer("I don't wanna be somebody")),
  L(cheer("Just wanna be me be me")),
  L(cheer("I wanna be me me me")),
  L(cheer("(欢呼!!!)")),
];

export const wannabeGuide: CheerGuide = {
  slug: "wannabe",
  title: "<WANNABE> 应援法",
  credit: "MADE BY @Ttwdm_susu",
  accent: "blue",
  columns: [LEFT, RIGHT],
};
