/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'gold.ts',
  exportName: 'goldGuide',
  slug: 'gold',
  title: '<GOLD> ' + T.yingyuan,
  accent: 'pink',
  left: [
    row(sp('c', T.cheerBang)),
    row(sp('l', '평온함을 rip 대혼란을 일으켜 '), sp('c', '够!')),
    row(sp('l', '본 적 없던 lit 내 본능을 깨워 '), sp('c', '的!')),
    row(sp('l', 'Going to my head,')),
    row(sp('l', 'going all out of control')),
    row(sp('l', 'Cuz I shine so bright like dynamite')),
    row(sp('l', 'GOLD')),
    row(sp('c', '있지! 믿지! ' + T.cheerBang)),
    row(sp('l', 'Yeah ITZY Yeah Ho ~')),
    row(sp('l', '쉴 새 없는 하루 Wait a minute')),
    row(sp('l', '문젠 없지 Wait a minute')),
    row(sp('l', '좀 더 재밌는 걸 찾아갈 뿐이지 What')),
    row(sp('l', 'Just keep it going up '), sp('c', 'up up up up')),
    row(sp('l', '그때 너를 발견한 거야')),
    row(sp('l', '두 눈이 마주친 다음')),
    row(sp('c', '(hey ~ ~ ~)')),
    row(sp('l', 'That thing that you do')),
    row(sp('l', 'That thing that you do')),
    row(sp('l', '불현듯이 내맘이 '), sp('c', '(hey ~ ~ ~)')),
    row(sp('l', 'Yeah diamond in my heart 반쯤 홀린 듯')),
    row(sp('c', "What's the deal")),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Always in my head')),
    row(sp('l', 'you a repeat of my '), sp('c', 'favorite song')),
    row(sp('l', '나의 머리엔 새로운 감정들이 느껴져')),
    row(sp('c', '咪揪')),
    row(sp('l', '완전히 다른 세상이 all around')),
    row(sp('l', "Get up, let's go another round")),
    row(sp('l', "It's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '눈을 뗄 수 없이 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "It's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '거부할 수 없이 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "Head to toe we're G-O-L-D "), sp('c', 'gold')),
    row(sp('l', 'Gold in the air, gold everywhere')),
    row(sp('l', '디딜 틈조차 없는 shadow 너라는 존재로')),
    row(sp('l', 'Hey 나는 이제')),
    row(sp('l', '저 멀리 빛나는 별보다 밝게 타오르게 돼')),
  ],
  right: [
    row(sp('c', '(hey ~ ~ ~)')),
    row(sp('l', 'What you want to do')),
    row(sp('l', 'What you want to do')),
    row(sp('l', '조금 위험한 느낌 '), sp('c', '(hey ~ ~ ~)')),
    row(sp('l', 'Yeah diamond in my heart')),
    row(sp('l', '가빠지는 숨')),
    row(sp('c', "What's the deal")),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Always in my head')),
    row(sp('l', 'you a repeat of my '), sp('c', 'favorite song')),
    row(sp('l', '나의 심장에 낯선 감정들이 느껴져')),
    row(sp('c', '咪揪')),
    row(sp('l', '완전히 다른 세상이 all around')),
    row(sp('l', "Get up, let's go another round")),
    row(sp('l', "It's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '눈을 뗄 수 없이 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "It's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '거부할 수 없이 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "Head to toe we're G-O-L-D "), sp('c', 'gold')),
    row(sp('c', T.members)),
    row(sp('c', '(永远永远 闪耀闪耀 just like that)')),
    row(sp('c', T.cheerBang)),
    row(sp('l', "It's like, it's like, it's like,")),
    row(sp('l', "it's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '계속 날 이끄는 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "It's like GOLD "), sp('c', '(G! O! L! D!)')),
    row(sp('l', '눈을 감아봐도 glow')),
    row(sp('c', 'Day and night we beaming blazing')),
    row(sp('c', 'just like that')),
    row(sp('l', "Head to toe we're G-O-L-D "), sp('c', 'gold')),
    row(sp('c', T.cheerBang)),
  ],
};
