/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'imaginary-friend.ts',
  exportName: 'imaginaryFriendGuide',
  slug: 'imaginary-friend',
  title: '<Imaginary Friend> ' + T.yingyuan,
  accent: 'pink',
  left: [
    row(sp('c', T.cheerBang)),
    row(sp('c', T.members)),
    row(sp('c', '(Itzy! Who are you?)')),
    row(sp('l', 'Who am I? The revolution')),
    row(sp('l', '깨어난 '), sp('c', 'your illusion')),
    row(sp('l', '상상 속에 your illusion')),
    row(sp('l', 'Oh 너의 '), sp('c', '상상 속에')),
    row(sp('l', '존재해 상상 속에')),
    row(sp('l', '숨쉬는 '), sp('c', 'fallen angel')),
    row(sp('l', 'Who am I? '), sp('c', 'fallen angel')),
    row(sp('l', "Oh I'm a fallen angel "), sp('c', 'and I said')),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Call out my name')),
    row(sp('l', 'in the middle of the night')),
    row(sp('l', '두려워 '), sp('c', '마 call out my name')),
    row(sp('l', 'call out my name yeah')),
    row(sp('l', 'Call out my name')),
    row(sp('l', 'in the middle of the night')),
    row(sp('l', '두려워 '), sp('c', '마 call out my name')),
    row(sp('l', "You know, I'm")),
    row(sp('l', 'your imaginary friend')),
    row(sp('l', "You know, I'm")),
    row(sp('l', '밤새 너의 곁에서')),
    row(sp('l', "When there's monsters")),
    row(sp('l', 'on your ceiling')),
    row(sp('l', "I'll keep you safe and")),
    row(sp('l', '꿈을 꿀 수 있게')),
    row(sp('l', "You know, I'm")),
    row(sp('l', 'your imaginary friend')),
    row(sp('l', "You know, I'm")),
    row(sp('l', "It's you and I until the end")),
    row(sp('c', '(Itzy! Midzy!)')),
    row(sp('c', T.cheerBang)),
    row(sp('c', T.members)),
    row(sp('c', '(Itzy! Who are you?)')),
  ],
  right: [
    row(sp('l', 'Who am I? The evolution')),
    row(sp('l', '기억 안에 '), sp('c', '존재해')),
    row(sp('l', '네 맘속 hallucination')),
    row(sp('l', 'Oh 너의 '), sp('c', '상상 속에')),
    row(sp('l', 'Come on and '), sp('c', 'dance, dance')),
    row(sp('l', "and don't stop")),
    row(sp('l', '작은 나의 '), sp('c', 'lucky spark')),
    row(sp('l', '네게 힘이 '), sp('c', '될 거야')),
    row(sp('l', 'We gon '), sp('c', 'ride and run')),
    row(sp('l', "can't stop thinking about our vibe")),
    row(sp('l', 'Jump '), sp('c', 'we can run')),
    row(sp('l', "and I'm killing it to the top yeah")),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Call out my name')),
    row(sp('l', 'in the middle of the night')),
    row(sp('l', '두려워 '), sp('c', '마 call out my name')),
    row(sp('l', 'call out my name yeah')),
    row(sp('l', 'Call out my name')),
    row(sp('l', 'in the middle of the night')),
    row(sp('l', '두려워 '), sp('c', '마 call out my name')),
    row(sp('l', "You know, I'm")),
    row(sp('l', 'your imaginary friend')),
    row(sp('l', "You know, I'm")),
    row(sp('l', '밤새 너의 곁에서')),
    row(sp('l', "When there's monsters")),
    row(sp('l', 'on your ceiling')),
    row(sp('l', "I'll keep you safe and")),
    row(sp('l', '꿈을 꿀 수 있게')),
    row(sp('l', "You know, I'm")),
    row(sp('l', 'your imaginary friend')),
    row(sp('l', "You know, I'm")),
    row(sp('l', "It's you and I until the end")),
    row(sp('c', T.cheerBang)),
    row(sp('c', T.members)),
    row(sp('c', '(Itzy! Midzy!)')),
  ],
};
