/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'loco.ts',
  exportName: 'locoGuide',
  slug: 'loco',
  title: '<LOCO> ' + T.yingyuan,
  accent: 'red',
  left: [
    row(sp('l', 'LOCO')),
    row(sp('c', T.members)),
    row(sp('c', '(Itzy?Midzy?LOCO?)')),
    row(sp('l', '미친다는 말이 이해 간달까')),
    row(sp('c', "I'm gettin' LOCO LOCO")),
    row(sp('l', 'Oh gosh 이건 달콤한 독 같아')),
    row(sp('c', "I'm gettin' LOCO LOCO")),
    row(sp('l', '출구 없는 방')),
    row(sp('l', '안에 사방이')),
    row(sp('l', '너란 거울이야')),
    row(sp('l', 'I feel like')),
    row(sp('l', 'I was born to love ya')),
    row(sp('l', '오아시스 찾는 Kitty')),
    row(sp('l', '난 네 주위를 맴돌지')),
    row(sp('l', '콩깍지 껴 버린 내 두 눈은 Yellow')),
    row(sp('l', '켜줘 네 손으로 불 꺼진 내 심장')),
    row(sp('l', "It's too late, "), sp('c', 'want you so bad')),
    row(sp('l', '너를 갖고 싶어졌어')),
    row(sp('l', '몰라 이젠 이미 난 Blind')),
    row(sp('l', '끝까지 가볼래')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '넌 날 반쯤 미치게 만들어')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '대체 네가 뭔데 '), sp('c', '미쳐')),
    row(sp('l', '미쳐 날뛰어 기분이 Up & Down')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '나도 내가 Outta control')),
    row(sp('c', "I'm gettin' LOCO LOCO")),
    row(sp('c', "I'm gettin' LOCO LOCO")),
    row(sp('l', '내게 대체 넌 뭘 원해 '), sp('c', '미쳐')),
    row(sp('l', '미친 이 마음은 다 갖다 퍼 줘도')),
    row(sp('c', "I'm ok")),
    row(sp('l', '하루는 천국을 갔다 왔다 가도')),
    row(sp('l', '나락 끝까지 날 밀어버려')),
  ],
  right: [
    row(sp('l', 'So dangerous,')),
    row(sp('c', 'so so so dangerous uh oh')),
    row(sp('l', '날 더 망가뜨려도')),
    row(sp('l', '널 믿을 수 밖에 없게 해줘')),
    row(sp('l', '오아시스 찾은 Kitty')),
    row(sp('l', '난 네 옆 자릴 넘보지')),
    row(sp('l', 'Break 따윈 잊었어 끝까지 가 볼래')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '넌 날 반쯤 미치게 만들어')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '대체 네가 뭔데 '), sp('c', '미쳐')),
    row(sp('l', '미쳐 날뛰어 기분이 Up & Down')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '나도 내가 Outta control')),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'LOCO')),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', 'oh oh oh')),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', 'oh oh oh')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '넌 날 완전 미치게 만들어')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '대체 네가 뭔데 '), sp('c', '미쳐')),
    row(sp('l', '미쳐 날뛰어 기분이 Up & Down')),
    row(sp('l', 'You got me like')),
    row(sp('c', 'CRAY CRAY CRAZY in love')),
    row(sp('l', '나도 내가 Outta control')),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', "I'm gettin' LOCO LOCO CO")),
    row(sp('c', T.cheerBang)),
  ],
};
