/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'not-shy.ts',
  exportName: 'notShyGuide',
  slug: 'not-shy',
  title: '<Not Shy> ' + T.yingyuan,
  accent: 'orange',
  left: [
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(yeah)')),
    row(sp('l', 'Not shy not me')),
    row(sp('c', '(Itzy ! Midzy ! Not shy ! 娜)')),
    row(sp('l', '난 빨리빨리 원하는 걸 말해')),
    row(sp('l', '못 가지면 어때 괜히 '), sp('c', '망설')),
    row(sp('l', '망설이다 시간만 가니')),
    row(sp('l', 'Yeah 다 말할래')),
    row(sp('l', 'cuz I like it cuz I '), sp('c', 'like it like it')),
    row(sp('l', '기다려 왜 기다려서 뭐해')),
    row(sp('l', '내가 내 맘을 왜 왜 말하면 안 돼 '), sp('c', 'yeah')),
    row(sp('l', '그냥 탁 '), sp('c', '탁탁탁탁탁')),
    row(sp('c', '탁탁탁탁탁')),
    row(sp('l', 'Not shy to say I want you')),
    row(sp('l', 'Hey there hey there 우리는 '), sp('c', '우리는')),
    row(sp('l', 'Great pair great pair 네 맘이 '), sp('c', '뭔지')),
    row(sp('l', '모르지만 내 생각이 맞아')),
    row(sp('l', '그러니까 '), sp('c', 'yeah yeah')),
    row(sp('l', '내 맘은 내 거 '), sp('c', '그러니까')),
    row(sp('l', '좋아한다고 '), sp('c', '자유니까')),
    row(sp('l', '네 맘은 네 거 '), sp('c', '맞으니까')),
    row(sp('l', '말해봐 다 어서 다 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', 'Give me 다 다다 '), sp('c', '다다다다다')),
    row(sp('c', '다다다다다')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', '너를 원해 뭐 어때 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '넌 빨리빨리 대답할 필욘 없어')),
    row(sp('l', '어차피 내 거니까 woo')),
    row(sp('l', '날 보고 있기만 하면 돼')),
    row(sp('l', 'Yeah you will like it cuz you like it')),
    row(sp('l', 'Cuz you '), sp('c', 'like it like it')),
    row(sp('l', '내가 미워 아니라면 비워')),
    row(sp('l', '다른 건 다 지워 내가 네 only one '), sp('c', 'yeah')),
    row(sp('l', '그냥 싹 '), sp('c', '싹싹싹싹싹')),
    row(sp('c', '싹싹싹싹싹')),
    row(sp('l', 'Not shy to say I want you')),
  ],
  right: [
    row(sp('l', 'Hey there hey there 우리는 '), sp('c', '우리는')),
    row(sp('l', 'Great pair great pair 네 맘이 '), sp('c', '뭔지')),
    row(sp('l', '모르지만 내 생각이 맞아')),
    row(sp('l', '그러니까 '), sp('c', 'yeah yeah')),
    row(sp('l', '내 맘은 내 거 '), sp('c', '그러니까')),
    row(sp('l', '좋아한다고 '), sp('c', '자유니까')),
    row(sp('l', '네 맘은 네 거 '), sp('c', '맞으니까')),
    row(sp('l', '말해봐 다 어서 다 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', 'Give me 다 다다 '), sp('c', '다다다다다')),
    row(sp('c', '다다다다다')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', '너를 원해 뭐 어때 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '후회하긴 싫으니까')),
    row(sp('l', '엔딩 상관없으니까')),
    row(sp('l', 'Go go go 모두 쏟아내')),
    row(sp('l', 'No yes no 뭐든지 어때')),
    row(sp('l', '이러면 저러면 어때')),
    row(sp('l', '어차피 안 될 거 빼고 다 돼')),
    row(sp('l', 'Let\u2019s just be who we are')),
    row(sp('l', 'Do what we do 네 맘대로 해')),
    row(sp('l', 'Let the beat drop')),
    row(sp('c', T.cheerBang)),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', '말해봐 다 어서 다 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', 'Give me 다 다다 '), sp('c', '다다다다다')),
    row(sp('c', '다다다다다')),
    row(sp('l', 'Not shy not me '), sp('c', '(ITZY)')),
    row(sp('l', '난 다 원해 다다 '), sp('c', '(not shy)')),
    row(sp('l', 'Not shy not me')),
    row(sp('l', '너를 원해 뭐 어때 cuz I\u2019m '), sp('c', 'not shy')),
    row(sp('c', 'Not shy not me')),
    row(sp('c', T.cheerBang)),
  ],
};
