/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'thats-a-no-no.ts',
  exportName: 'thatsANoNoGuide',
  slug: 'that-s-a-no-no',
  title: "<THAT'S A NO NO> " + T.yingyuan,
  accent: 'blue',
  left: [
    row(sp('c', T.cheerBang)),
    row(sp('c', T.members)),
    row(sp('c', "(Itzy ! That's ! a ! no ! no ! )")),
    row(sp('l', '어떤 말을 해도 난 난 난')),
    row(sp('l', '내가 원하는 대로')),
    row(sp('l', '난 난 난 난 난')),
    row(sp('c', '拍手')),
    row(sp('l', 'Well made label on my body')),
    row(sp('c', 'Oooh move up faster faster')),
    row(sp('c', "Oooh gettin' louder louder")),
    row(sp('c', "Oooh 내 말대로 That's all")),
    row(sp('l', '뭐라 해도 Don\u2019t ask no questions')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '뭐라 해도 내 말대로 말해')),
    row(sp('l', "Can't let you kill my vibe")),
    row(sp('c', "that's a no no")),
    row(sp('l', 'Sorry, I beg your pardon')),
    row(sp('l', '뭐라 해도 내 말대로 I told ya')),
    row(sp('l', "That's a no no")),
    row(sp('c', 'Hoo Ah ya ya ya ya')),
    row(sp('c', 'Ha uh uh uh')),
    row(sp('c', 'Hoo ah ya ya ya ya')),
    row(sp('l', 'Do what I want Say what I wanna')),
    row(sp('c', 'Hoo Ah ya ya ya ya')),
    row(sp('c', 'Ha uh uh uh')),
    row(sp('c', 'Hoo ah ya ya ya ya')),
    row(sp('l', 'Do what I want Say what I wanna')),
    row(sp('l', 'Hit that thang like a drum '), sp('c', 'ta ta')),
    row(sp('l', 'Rum pa pa pum pa pa pum '), sp('c', 'pa pa')),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('l', '말해 '), sp('c', '说'), sp('l', ' 말해 '), sp('c', '说 说')),
    row(sp('c', '拍手')),
  ],
  right: [
    row(sp('l', 'Blow that thang')),
    row(sp('l', 'like a brass '), sp('c', 'bam bam')),
    row(sp('l', 'Rum pa pa pum pa pa pum '), sp('c', 'pa pa')),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('l', "Say that's a "), sp('c', 'no no'), sp('l', " that's a "), sp('c', 'no no')),
    row(sp('c', T.cheerBang)),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('l', '뭐라 해도 That\u2019s no, I\u2019m sorry')),
    row(sp('l', "I'm gonna keep singing")),
    row(sp('l', "I'm gonna keep dancing")),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('c', "That's ! a ! no ! no !")),
    row(sp('l', 'Hit that thang like a drum '), sp('c', 'ta ta')),
    row(sp('l', 'Rum pa pa pum pa pa pum '), sp('c', 'pa pa')),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('l', '말해 '), sp('c', '说'), sp('l', ' 말해 '), sp('c', '说 说')),
    row(sp('c', '拍手')),
    row(sp('l', 'Blow that thang')),
    row(sp('l', 'like a brass '), sp('c', 'bam bam')),
    row(sp('l', 'Rum pa pa pum pa pa pum '), sp('c', 'pa pa')),
    row(sp('l', '뭐라 해도 내 말대로')),
    row(sp('l', "Say that's a "), sp('c', 'no no'), sp('l', " that's a "), sp('c', 'no no')),
    row(sp('c', 'Hoo Ah ya ya ya ya')),
    row(sp('c', 'Ha uh uh uh')),
    row(sp('c', 'Hoo ah ya ya ya ya')),
    row(sp('l', "That's a no no")),
    row(sp('c', 'Hoo Ah ya ya ya ya')),
    row(sp('c', 'Ha uh uh uh')),
    row(sp('c', 'Hoo ah ya ya ya ya')),
    row(sp('l', "That's a no no")),
    row(sp('c', T.cheerBang)),
  ],
};
