/* eslint-disable */
const { T } = require('../_emit_lib.cjs');
const { sp, row } = require('./_helpers.cjs');

module.exports = {
  file: 'tunnel-vision.ts',
  exportName: 'tunnelVisionGuide',
  slug: 'tunnel-vision',
  title: '<TUNNEL VISION> ' + T.yingyuan,
  accent: 'red',
  left: [
    row(sp('c', T.cheerBang)),
    row(sp('c', 'Yeah !')),
    row(sp('c', 'Yeah !')),
    row(sp('c', 'Yeah ! yeah !')),
    row(sp('l', 'Eyes on the quest')),
    row(sp('l', "I don't take "), sp('c', 'vacation')),
    row(sp('l', '잠 못 들어도')),
    row(sp('l', 'cause I got that '), sp('c', 'patience')),
    row(sp('l', '한계점은 nah '), sp('c', 'ambition')),
    row(sp('l', "I'll show my reign")),
    row(sp('l', '집중 '), sp('c', 'standing ovation')),
    row(sp('l', 'Small talk? pass')),
    row(sp('l', 'I worked hard for this')),
    row(sp('l', 'Got my poker face 날 예측 못해')),
    row(sp('l', '알아 what\u2019s my game')),
    row(sp('l', '목표는 '), sp('c', 'never miss')),
    row(sp('c', 'never miss !')),
    row(sp('c', 'Work work work')),
    row(sp('l', '시선은 focused grindin\u2019 till I score')),
    row(sp('l', '가치를 높여 '), sp('c', 'worth worth worth')),
    row(sp('l', 'Keep my altitude 지켜 나를 더')),
    row(sp('l', 'Now I better pause 모두 집중 on alert')),
    row(sp('l', 'Never backing down')),
    row(sp('l', '내가 찾은 what I want '), sp('c', '(want!)')),
    row(sp('c', T.cheerBang)),
    row(sp('l', "Nothing's gonna put me off")),
    row(sp('l', '빛이 '), sp('c', '날 비춰')),
    row(sp('l', 'I know what the hell I want')),
    row(sp('l', "Don't need "), sp('c', 'permission')),
    row(sp('l', '어둠 속 나를 넘어 '), sp('c', 'my motivation')),
    row(sp('l', 'Focus on my level up')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('l', 'Expanded version 2.0')),
    row(sp('l', '한계를 태우고 만든 paceset')),
    row(sp('l', 'Hop in my lane oh fast fast so long')),
    row(sp('c', 'Work work work')),
    row(sp('l', '시선은 focused grindin\u2019 till I score')),
    row(sp('l', '가치를 높여 '), sp('c', 'worth worth worth')),
    row(sp('l', 'Keep my altitude 지켜 나를 더')),
    row(sp('l', 'Now I better pause 모두 집중 on alert')),
    row(sp('l', 'Never backing down')),
    row(sp('l', '빛을 쫓아 what I want '), sp('c', '(want!)')),
  ],
  right: [
    row(sp('c', T.cheerBang)),
    row(sp('l', "Nothing's gonna put me off")),
    row(sp('l', '빛이 '), sp('c', '날 비춰')),
    row(sp('l', 'I know what the hell I want')),
    row(sp('l', "Don't need "), sp('c', 'permission')),
    row(sp('l', '어둠 속 나를 넘어 '), sp('c', 'my motivation')),
    row(sp('l', 'Focus on my level up')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('l', 'Never lose my sight 전부 '), sp('c', '걸어 (걸어)')),
    row(sp('l', "Keep it up I'm a stunner "), sp('c', '(stunner!)')),
    row(sp('l', '시작해 making the buzz')),
    row(sp('l', '내 vision은 언제나 plus')),
    row(sp('l', 'Celebrate I toast 피어난 꿈은 rose')),
    row(sp('l', 'Stack it up, stack it up on my own')),
    row(sp('l', "I don't flex, all the risk 이겨내 here I go")),
    row(sp('c', '(Go go go go go go go go)')),
    row(sp('l', 'Focus '), sp('c', '(whoo)')),
    row(sp('c', T.cheerBang)),
    row(sp('l', "Nothing's gonna put me off")),
    row(sp('l', '빛이 '), sp('c', '날 비춰')),
    row(sp('l', 'I know what the hell I want')),
    row(sp('l', "Don't need "), sp('c', 'permission')),
    row(sp('l', '어둠 속 나를 넘어 '), sp('c', 'my motivation')),
    row(sp('l', 'Focus on my level up')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya h ya')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya ah')),
    row(sp('l', 'Ya ah ya, ya ah ya')),
    row(sp('l', 'I got '), sp('c', 'tunnel vision')),
    row(sp('c', '(黄~礼志 崔智秀! 申~留真 李彩领! 申~有娜 Itzy ! Midzy !)')),
    row(sp('c', '(Itzy ! Midzy !)')),
    row(sp('l', 'I got tunnel vision')),
    row(sp('c', T.cheerBang)),
  ],
};
